Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -154,7 +154,7 @@ jobs:
           terraform apply --var-file production.tfvars --auto-approve 
           echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> "$GITHUB_ENV"
           echo "SERVICE_NAME=$(terraform output -raw service_name)" >> "$GITHUB_ENV"
-          echo "TASK_DEFINITION=$(terraform output -raw task_definition | sed 's|.*/||')"
+          echo "TASK_DEFINITION=$(terraform output -raw task_definition | grep -Eo 'task-definition/[^ ]+' | cut -d'/' -f2 | tr -d '\n' || echo "ERROR")" >> "$GITHUB_ENV"
         working-directory: tasks/ecs_update/
 
       - name: Fetch Latest Task Definition
